# Generated by Django 4.2.1 on 2023-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installation_number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('generated_power', models.FloatField()),
                ('consumed_power', models.FloatField()),
                ('vertical_position', models.IntegerField()),
                ('horizontal_position', models.IntegerField()),
            ],
        ),
    ]
