# Generated by Django 4.2.2 on 2023-06-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ip_remove_reading_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ip'),
        ),
    ]
