# Generated by Django 4.2.2 on 2023-06-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_reading_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='ip',
        ),
        migrations.AddField(
            model_name='ip',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reading'),
        ),
    ]
