# Generated by Django 4.2 on 2023-10-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_reading_ip_ip_reading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'ordering': ['-ip_address']},
        ),
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-installation_number']},
        ),
    ]
