# Generated by Django 4.2 on 2023-10-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ip_options_alter_reading_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('generated_power', models.FloatField()),
                ('consumed_power', models.FloatField()),
                ('vertical_position', models.IntegerField()),
                ('horizontal_position', models.IntegerField()),
            ],
            options={
                'ordering': ['-date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Solar_Panel',
            fields=[
                ('installation_number', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(default='', max_length=15)),
                ('port', models.CharField(default='', max_length=5)),
            ],
            options={
                'ordering': ['-installation_number'],
            },
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.AddField(
            model_name='characteristics',
            name='Solar_Panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.solar_panel'),
        ),
    ]
