# Generated by Django 4.2 on 2023-10-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_characteristics_solar_panel_delete_ip_delete_reading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristics',
            old_name='Solar_Panel',
            new_name='solar_Panel',
        ),
    ]
