# Generated by Django 4.2.6 on 2023-11-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_solar_panel_characteristics_solar_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('date', models.DateTimeField()),
                ('solar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.solar_panel')),
            ],
            options={
                'db_table': 'solar_statement',
            },
        ),
    ]
