# Generated by Django 4.2.7 on 2023-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_solarstatement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solar_panel',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='solar_panel',
            old_name='installation_number',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='solarstatement',
            old_name='solar_id',
            new_name='solar_panel',
        ),
        migrations.AddField(
            model_name='solarstatement',
            name='command',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
