# Generated by Django 4.2.7 on 2023-12-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_solar_panel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristics',
            name='battery',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characteristics',
            name='options',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characteristics',
            name='status',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characteristics',
            name='weather',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solar_panel',
            name='coordinates',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solar_panel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solar_panel',
            name='type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
