# Generated by Django 4.2.7 on 2023-12-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_characteristics_battery_characteristics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='solar_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.solar_panel'),
        ),
        migrations.AlterField(
            model_name='solarstatement',
            name='solar_panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.solar_panel'),
        ),
    ]
