# Generated by Django 4.2.7 on 2023-12-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_characteristics_solar_panel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='battery',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characteristics',
            name='weather',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solar_panel',
            name='coordinates',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solar_panel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solar_panel',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
